(function(g){var window=this;'use strict';var xob=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.jdb)("0",Math.max(0,b-c))+a},yob=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},zob=function(){return{I:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{I:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},Bob=function(a){"number"===typeof a?(this.date=Aob(a,0,1),y6(this,1)):g.$a(a)?(this.date=Aob(a.getFullYear(),a.getMonth(),a.getDate()),y6(this,a.getDate())):(this.date=new Date(g.ib()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),y6(this,a))},Aob=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},y6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},z6=function(a,b){g.wU.call(this,a,{I:"div",
S:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},V:[{I:"div",S:"ytp-reminder-menu-contents",V:[{I:"div",S:"ytp-reminder-menu-items"}]}]},100,!0);this.buttonElement=b;this.j=[];this.menuPopupRenderer=void 0;this.items=this.Fa("ytp-reminder-menu-items");this.hide()},Dob=function(a){var b=Cob(a),c=0,d={};
for(c=0;c<b.length;d={gO:d.gO},c++){var e=a.j[c];e||(e=new g.U({I:"div",S:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},V:[{I:"div",S:"ytp-reminder-menu-item-icon",xa:"{{icon}}"},{I:"div",S:"ytp-reminder-menu-item-label",xa:"{{text}}"}]}),d.gO=c,e.Sa("click",function(l){return function(){var m=l.gO;a.Ob();m=Cob(a)[m];a.oa("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ea(a.items),a.j[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=yob();break;case "NOTIFICATIONS_NONE":h=zob();break;case "NOTIFICATIONS_ACTIVE":h=g.Sua()}f=f.text?g.qG(f.text):"";e.update({icon:h,text:f})}for(;c<a.j.length;)a.j.pop().dispose();0===c?a.Ob():a.xd(a.buttonElement)},Cob=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},A6=function(a){g.U.call(this,{I:"div",
V:[{I:"button",Ma:["ytp-offline-slate-button","ytp-button"],V:[{I:"div",S:"ytp-offline-slate-button-icon",xa:"{{icon}}"},{I:"div",S:"ytp-offline-slate-button-text",xa:"{{text}}"}]}]});this.J=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.B=void 0;this.D=this.j=null;(this.buttonElement=this.Fa("ytp-offline-slate-button"))&&this.T(this.buttonElement,"click",this.G);this.hide()},Fob=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=
b.toggleButtonRenderer:b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&g.S(c,Eob)?a.upcomingEventReminderButtonRenderer=g.S(c,Eob):c&&g.S(c,Eob)||(a.upcomingEventReminderButtonRenderer=null);B6(a)},B6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.qG(b.toggledText):"";a.update({text:c,icon:Gob(b.toggledIcon)})}else c=b.defaultText?g.qG(b.defaultText):"",a.update({text:c,icon:Gob(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=Hob(a))?(c=b.text?g.qG(b.text):"",a.update({text:c,icon:Gob(b.icon)}),a.show()):a.hide():a.hide()},Job=function(a,b,c){a.D||(a.D=new g.HE(a.J.U().jl));
var d={context:g.zqa(a.D.config_||g.gE())};g.KF()&&(d.context.clientScreenNonce=g.KF());d.params=c;g.IE(a.D,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.B&&(a.upcomingEventReminderButtonRenderer.currentState=a.B,a.B=void 0)},
onError:function(){Iob(a)},
onTimeout:function(){Iob(a)}})},Iob=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,B6(a)):a.upcomingEventReminderButtonRenderer&&(a.B=void 0,B6(a))},Gob=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return yob();case "NOTIFICATIONS_NONE":return zob();case "NOTIFICATIONS_ACTIVE":return g.Sua();default:return null}},Hob=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.B||a.upcomingEventReminderButtonRenderer.currentState;a=g.u(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=g.S(c.value,Kob))&&c.state===b&&c.button&&g.S(c.button,g.iN))return g.S(c.button,g.iN);return null},Lob=function(a){g.U.call(this,{I:"div",
S:"ytp-offline-slate",V:[{I:"div",S:"ytp-offline-slate-background"},{I:"div",S:"ytp-offline-slate-bar",V:[{I:"span",S:"ytp-offline-slate-icon",V:[{I:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{I:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{I:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{I:"span",S:"ytp-offline-slate-messages",V:[{I:"div",S:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},xa:"{{mainText}}"},{I:"div",S:"ytp-offline-slate-subtitle-text",xa:"{{subtitleText}}"}]},{I:"span",S:"ytp-offline-slate-buttons"}]},{I:"button",Ma:["ytp-offline-slate-close-button","ytp-button"],V:[g.tG()]},{I:"button",Ma:["ytp-offline-slate-open-button","ytp-button"],V:[g.sG()]}]});var b=this;this.api=a;this.j=this.B=null;this.background=this.Fa("ytp-offline-slate-background");
this.C=this.Fa("ytp-offline-slate-bar");this.G=new g.eu(function(){g.mu(b.C,"ytp-offline-slate-bar-fade")},15E3);
this.K=!1;this.D=new g.eu(function(){g.mu(b.element,"ytp-offline-slate-collapsed")},15E3);
g.L(this,this.D);g.L(this,this.G);this.countdownTimer=new g.eu(this.C_,1E3,this);this.T(a,"presentingplayerstatechange",this.G_);this.T(a,"livestatedata",this.Qa);a=this.Fa("ytp-offline-slate-close-button");this.T(a,"click",function(){g.mu(b.element,"ytp-offline-slate-collapsed")});
a=this.Fa("ytp-offline-slate-open-button");this.T(a,"click",function(){g.ou(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.Qa(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().Ol;var c=8===this.api.getPresentingPlayerType();g.qu(this.element,"ytp-offline-slate-premiere-trailer",a);g.qu(this.element,"ytp-offline-slate-hide-background",c)},Mob=function(a,b,c){if(b){var d=null!=b.subtitleText?g.qG(b.subtitleText):"";
c=c?c:null!=b.mainText?g.qG(b.mainText):"";var e,f,h,l;b=null!=(l=null==(e=b.mainText)?void 0:null==(f=e.accessibility)?void 0:null==(h=f.accessibilityData)?void 0:h.label)?l:c;a.update({mainText:c,subtitleText:d,label:b});g.qu(a.element,"ytp-offline-slate-single-text-line",!d);g.qu(a.C,"ytp-offline-slate-bar-hidden",!c&&!d)}},C6=function(a,b){var c=(0,g.GD)();
this.module="heartbeat";this.trigger=a;this.j=b;this.C=c},Uob=function(a){g.xV.call(this,a);
var b=this;this.N=!1;this.Z=0;this.G=!1;this.B=new g.eu(function(){var e=b.player.U(),f=b.getVideoData();D6(b)&&(Nob(b)?Oob(b,e,f):(Pob(b),Qob(b,e,f)))},0);
this.j=this.heartbeatParams=null;this.D=!1;this.K=new g.ql(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.ma=new g.HE(void 0);this.Y=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new Bob).getTimezoneOffset();this.C=new g.TK(this);g.L(this,this.B);g.L(this,this.C);Pob(this);Rob(this);this.C.T(a,"heartbeatparams",this.sE);this.C.T(a,"presentingplayerstatechange",this.e1);this.C.T(a,"videoplayerreset",this.f1);this.C.T(a,g.jK("heartbeat"),this.onCueRangeEnter);this.D&&this.j&&
Sob(this,void 0,this.j);var c=new g.iK(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.iK(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.tf([c,d]);Tob(this)},Tob=function(a){var b=a.getVideoData();
b.Hl&&(b=b.botguardData)&&g.TKa(b,a.player.U())},Pob=function(a){var b=a.getVideoData();
if(b.Hl&&(b=new g.PKa(b),g.sI.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Gk){var d=g.QKa(b);if(d){c={};var e={};d=d.split("&");d=g.u(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=Vob[Number(e.r1c)]);c.challenge=b.videoData.Gk}}a.attestationResponse=c||void 0}},Nob=function(a){var b=a.getVideoData();
if(!g.zT(a.getVideoData())||b.eZ)return!1;if(b.useInnertubeDrmService()&&b.K){a="playready"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_playready");var c="widevine"===b.K.flavor&&b.L("html5_innertube_heartbeats_for_widevine");b=g.AR(b.K)&&b.L("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},Wob=function(a){if(Nob(a))return!!a.heartbeatParams;
var b=a.getVideoData();return g.zT(a.getVideoData())&&b.useInnertubeDrmService()&&!b.Dl&&!b.cC?!1:!!b.heartbeatToken},E6=function(a,b){if(!a.B.isActive()&&a.N){var c=a.getVideoData();
if(Wob(a)||c.isLivePlayback){if(void 0===b)if(a.G)if(a.D)b=7500;else{var d;b=(null==(d=a.heartbeatParams)?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().iX||6E4}else b=1E3;a.B.start(b)}}},$ob=function(a,b,c){b.Do&&(c=g.Cl(c,{internalipoverride:b.Do}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.wb&&(d.kpt=b.wb);c=g.Cl(c,d);g.gC(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.B.isActive()&&D6(a)){a.K.reset();a.sequenceNumber++;e=e.responseText;var f=Xob(e);if(f){a.player.Ra("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(Yob))?"0"===h[1]?0:1:-1;Zob(a,void 0,f,e,h)}},
onError:function(e){D6(a)&&F6(a,!0,"net-"+e.status)},
onTimeout:function(){D6(a)&&F6(a,!0,"timeout")},
withCredentials:!0})},Oob=function(a,b,c){var d;
if(null!=(d=a.heartbeatParams)&&d.url){var e=g.Cl(a.heartbeatParams.url,{request_id:g.Sra()});c.qa&&(e=g.Cl(e,{vvt:c.qa}),c.mdxEnvironment&&(e=g.Cl(e,{mdx_environment:c.mdxEnvironment})));g.AS(b,c.oauthToken).then(function(f){f&&(e=g.Cl(e,{access_token:f}));$ob(a,c,e)})}},D6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.VG(a.player.Tb(a.getPlayerType()),4)?!1:Wob(a)||b.isLivePlayback?!0:(G6(a),!1)},Qob=function(a,b,c){var d,e={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!=(d=a.qa)?d:c.heartbeatServerData};a.Y=a.attestationResponse;c.Hl&&(e.attestationResponse=a.Y);var f=g.UT(c),h;d=null!=(h=f.client)?h:{};d.utcOffsetMinutes=a.utcOffsetMinutes;e.context=f;e.cpn=c.clientPlaybackNonce;if(h="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)d.timeZone=h;h={heartbeatChecks:[]};if(d=c.getPlayerResponse())c.heartbeatToken&&(e.heartbeatToken=c.heartbeatToken),(d=d.playabilityStatus)&&
(d=d.liveStreamability)&&d.liveStreamabilityRenderer&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.MJ(b)){h.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");f=apb(a);d={};null!==f&&(d.clientPlayerPositionUtcMillis=f);var l,m;f=(null==(m=null==(l=a.player.Eb())?void 0:g.MV(l))?void 0:m.freePreviewWatchedDuration)||0;0<f&&(d.freePreviewWatchedDuration={seconds:""+f});h.unpluggedParams=d}e.heartbeatRequestParams=
h;c.isLivePlayback?(l=apb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={utcTimeMillis:l})):b.L("enable_heartbeat_vod_playback_position")&&(l=bpb(a),null!==l&&(e.playbackState||(e.playbackState={}),e.playbackState.playbackPosition={streamTimeMillis:l}));a.player.oa("heartbeatRequest",e);var n={timeout:3E4,onSuccess:function(p){if(!a.B.isActive()&&D6(a)){var q=a.getVideoData(),r=q.Hl&&null==a.Y,t;q.Hl=!(null==(t=p.heartbeatAttestationConfig)||!t.requiresAttestation)||
r;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.va("authshear",{});var v=-1;var x=p.playabilityStatus;x&&(a.player.Ra("onHeartbeat",x),"OK"===x.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?v=1:"LIVE_STREAM_OFFLINE"===x.status&&(v=0));a.sequenceNumber&&-1===v||a.K.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.qa=p.heartbeatServerData);q.eC=p;(x=p.playerCueRangeSet)&&g.AQa(q,x);p.playerCueRanges&&0<p.playerCueRanges.length&&(q.cueRanges=p.playerCueRanges);
var C,G;(null==(C=p.progressBarConfig)?0:C.progressBarStartPosition)&&(null==(G=p.progressBarConfig)?0:G.progressBarEndPosition)&&(q.progressBarStartPosition=p.progressBarConfig.progressBarStartPosition,q.progressBarEndPosition=p.progressBarConfig.progressBarEndPosition);q.compositeLiveIngestionOffsetToken=p.compositeLiveIngestionOffsetToken;p.compositeLiveStatusToken!==q.compositeLiveStatusToken&&(q.compositeLiveStatusToken=p.compositeLiveStatusToken);q.oa("dataupdated");Zob(a,p,r,t,v)}},
onError:function(p){D6(a)&&F6(a,!0,"net-"+p.status)},
onTimeout:function(){D6(a)&&F6(a,!0,"timeout")}};
g.AS(b,g.PT(c)).then(function(p){p&&(n.DU="Bearer "+p);g.IE(a.ma,"player/heartbeat",e,n)})},Zob=function(a,b,c,d,e){-1===e?(c="decode "+g.lg(d,3),F6(a,!1,c)):2===e?(G6(a),a.G=!0):(a.Z=0,a.B.stop(),1===e?(a.G=!1,c&&"PLAYABILITY_ERROR_CODE_EMBARGOED"===c.errorCode&&a.player.Vn(!0),a.player.Rg("heartbeat.stop",2,a.uf(d)),g.rD("heartbeatActionPlayerHalted",cpb(c)),(null==b?0:b.videoTransitionEndpoint)&&c&&(b=b.videoTransitionEndpoint,(d=g.S(b,g.pT))&&dpb(a,d,c,{itct:null==b?void 0:b.clickTrackingParams}))):
(a.G=!0,d=0,a.D&&c&&(d=Sob(a,b,c),a.player.oa("livestatedata",c)),d?E6(a,d):E6(a)))},Sob=function(a,b,c){var d=c.liveStreamability&&c.liveStreamability.liveStreamabilityRenderer,e=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&"STREAM_TRANSITION_TIMING_IMMEDIATELY"===d.transitionTiming));
b=epb(a,b,d);var f=a.getVideoData(),h=a.player.Tb(a.getPlayerType()),l=h.isPlaying()&&!g.ET(f)&&!a.player.isAtLiveHead(a.getPlayerType());if(f.U().Wc()){var m,n=(null==(m=a.player.wf())?void 0:m.vc())||{};n.status=c.status||"";n.dvr=""+ +l;n["switch"]=""+ +e;n.ended=""+ +!(!d||!d.displayEndscreen);a.player.va("heartbeat",n)}if(l&&!e)return b;e=d&&d.streamTransitionEndpoint&&g.S(d.streamTransitionEndpoint,g.pT);if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(d&&d.transitionTiming))a.getVideoData().transitionEndpointAtEndOfStream=
e;else if(e&&dpb(a,e,c))return b;if("OK"===c.status.toUpperCase()){e=d&&d.broadcastId;m=a.j&&a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer&&a.j.liveStreamability.liveStreamabilityRenderer.broadcastId;l=e!==m&&null!=e;if(!fpb(a,f)||l){var p={video_id:f.videoId};f.ML&&(p.is_live_destination="1");a.player.L("web_player_heartbeat_request_watch_next")||(p.disable_watch_next=!0,p.raw_watch_next_response=f.Hd);p.autonav_state=f.autonavState;p.oauth_token=f.oauthToken;p.force_gvi=
f.Co;p.qm=f.qm;f.G&&(p.vss_credentials_token=f.G,p.vss_credentials_token_type=f.Em);f.qa&&(p.vvt=f.qa);d=void 0;fpb(a,f)?l&&(d=new C6("broadcastIdChanged",m+","+e),a.BI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",c)):(e&&(d=new C6("formatsReceived",""+e)),a.BI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",c));a.player.loadVideoByPlayerVars(p,void 0,void 0,void 0,d);return b}a.player.Eg("heartbeat",
a.getPlayerType())}d&&d.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.K=!0,a.Gb&&a.api.dB()):g.RL(h)&&(f=(null==(p=a.player.wf())?void 0:p.vc())||{},a.player.va("hbse",f,!0),a.player.dB(),a.player.Ra("onLiveMediaEnded",c)));return b},fpb=function(a,b){return a.player.L("web_player_heartbeat_has_media_urls")?g.CT(b):!(!b.hlsvp&&!b.Qb)},epb=function(a,b,c){return a.player.L("web_player_use_heartbeat_poll_delay_ms")&&(a=Number(null==b?void 0:b.pollDelayMs))?a:(c=Number(null==c?void 0:c.pollDelayMs))?
c:0},F6=function(a,b,c){var d=a.player.U();
if(!a.B.isActive()){a.B.stop();a.Z++;var e=b?"heartbeat.net":"heartbeat.servererror";var f=a.getVideoData();if(f.JX||b&&!g.zT(a.getVideoData())&&!Wob(a)&&f.isLivePlayback)f=!1;else{var h,l;(null==(l=a.heartbeatParams)?0:l.UA)?h=a.heartbeatParams.UA:h=f.tX||5;f=a.Z>=h}f?(g.rD("heartbeatActionPlayerHalted",b?{enforcedPolicyToHaltOnNetworkFailure:!0}:cpb()),(b=a.getVideoData())&&b.isLivePlayback?a.player.Rg(e,1,"Video playback interrupted. Please try again.",c):a.player.Rg(e,1,"Sorry, there was an error licensing this video.",
c)):(d.L("html5_report_non_fatal_heartbeat_error")&&a.player.Gr(e,{msg:c}),E6(a,a.K.getValue()),g.rl(a.K))}},cpb=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},G6=function(a){a.Z=0;
a.B.stop();a.G=!1;a.sequenceNumber=0},Rob=function(a){var b=a.getVideoData(),c=a.player.U();
if(b.isLivePlayback)if(g.qOa(c.G)){a.D=!0;a.N=!0;if(!g.OJ(c)||g.MJ(c))a.offlineSlate=new Lob(a.player),g.L(a,a.offlineSlate),g.qU(a.player,a.offlineSlate.element,4);(b=b.getPlayerResponse())&&b.playabilityStatus&&(a.j=b.playabilityStatus);var d;"UNPLAYABLE"!==(null==(d=a.j)?void 0:d.status)&&(a.j?(d=epb(a,void 0,a.j.liveStreamability&&a.j.liveStreamability.liveStreamabilityRenderer))?E6(a,d):E6(a,7500):E6(a,1E3))}else a.player.Rg("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");
else g.Db(b.Da,"heartbeat")&&a.player.Eg("heartbeat",a.getPlayerType())},dpb=function(a,b,c,d){var e=b&&b.videoId;
return e?(a.player.xo(e,Object.assign({},{autonav:"1"},d||{}),void 0,!0,!0,b,g.PT(a.getVideoData())),a.BI("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",c),!0):!1},apb=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},bpb=function(a){return(a=a.player.getCurrentTime(a.getPlayerType()))&&isFinite(a)?""+Math.floor(1E3*a):null},Xob=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},gpb={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},hpb=gpb;hpb=gpb;var Vob=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"];g.k=Bob.prototype;g.k.GV=hpb.FIRSTDAYOFWEEK;g.k.HV=hpb.FIRSTWEEKCUTOFFDAY;
g.k.clone=function(){var a=new Bob(this.date);a.GV=this.GV;a.HV=this.HV;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getYear=function(){return this.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.getTime=function(){return this.date.getTime()};
g.k.getDay=function(){return this.date.getDay()};
g.k.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.k.getUTCMonth=function(){return this.date.getUTCMonth()};
g.k.getUTCDate=function(){return this.date.getUTCDate()};
g.k.getUTCDay=function(){return this.date.getDay()};
g.k.getUTCHours=function(){return this.date.getUTCHours()};
g.k.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.k.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.setFullYear=function(a){this.date.setFullYear(a)};
g.k.setYear=function(a){this.setFullYear(a)};
g.k.setMonth=function(a){this.date.setMonth(a)};
g.k.setDate=function(a){this.date.setDate(a)};
g.k.setTime=function(a){this.date.setTime(a)};
g.k.setUTCFullYear=function(a){this.date.setUTCFullYear(a)};
g.k.setUTCMonth=function(a){this.date.setUTCMonth(a)};
g.k.setUTCDate=function(a){this.date.setUTCDate(a)};
g.k.add=function(a){if(a.years||a.months){var b=this.getMonth()+a.months+12*a.years,c=this.getYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(c);this.setMonth(b);this.setDate(d)}a.days&&(c=this.getYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.setDate(1),this.setFullYear(a.getFullYear()+
b),this.setMonth(a.getMonth()),this.setDate(a.getDate()),y6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getYear()!=a.getYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+xob(Math.abs(a),b?6:4),xob(this.getMonth()+1,2),xob(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};var ipb=new g.Nv("addUpcomingEventReminderEndpoint");var jpb=new g.Nv("removeUpcomingEventReminderEndpoint");var kpb=new g.Nv("updateUpcomingEventReminderButtonStateCommand");var Eob=new g.Nv("upcomingEventReminderButtonRenderer"),Kob=new g.Nv("upcomingEventReminderButtonStateRenderer");g.w(z6,g.wU);z6.prototype.hide=function(){this.buttonElement&&this.buttonElement.removeAttribute("aria-haspopup");g.wU.prototype.hide.call(this)};
z6.prototype.show=function(){this.buttonElement&&this.buttonElement.setAttribute("aria-haspopup","true");g.wU.prototype.show.call(this)};
z6.prototype.ya=function(){g.tb(this.j);g.wU.prototype.ya.call(this)};g.w(A6,g.U);
A6.prototype.G=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.C(a.toggledServiceEndpoint):this.C(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;B6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.j&&this.j.Gb)this.j.Ob();else{var b=Hob(this);b&&this.C(b.serviceEndpoint||b.command);b=(null==(a=g.S(null==b?void 0:b.command,g.cG))?void 0:a.commands)||[];a:{a=g.u(b);for(var c=a.next();!c.done;c=a.next()){var d=b=void 0;if(c=null==(b=g.S(c.value,
g.Veb))?void 0:null==(d=b.popup)?void 0:d.menuPopupRenderer){a=c;break a}}a=void 0}this.j||(this.j=new z6(this.J,this.buttonElement),this.j.Ea(this.element),g.L(this,this.j),this.j.subscribe("reminderMenuItemClicked",this.C,this));b=this.j;b.menuPopupRenderer=a;Dob(b)}};
A6.prototype.C=function(a){var b=g.S(a,ipb),c=g.S(a,jpb);if(a&&(b||c)){if(b){var d=b;var e="notification/add_upcoming_event_reminder"}else c&&(d=c,e="notification/remove_upcoming_event_reminder");if(e&&d&&d.params)for(Job(this,e,d.params),a=g.u(d.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&g.S(b,kpb)){this.B=g.S(b,kpb).state;B6(this);break}}};g.w(Lob,g.U);g.k=Lob.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.Qa=function(a){var b,c,d=null==a?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:c.offlineSlate;if(d){this.B=a;b=d.liveStreamOfflineSlateRenderer;b.canShowCountdown?this.C_():Mob(this,b);var e,f,h,l;if(c=null==a?void 0:null==(e=a.liveStreamability)?void 0:null==(f=e.liveStreamabilityRenderer)?void 0:null==(h=f.offlineSlate)?void 0:null==(l=h.liveStreamOfflineSlateRenderer)?void 0:l.thumbnail){e=0;f=null;h=c.thumbnails;for(l=0;l<h.length;l++)h[l].width>
e&&(e=h[l].width||0,f=h[l].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";b.actionButtons||b.reminderButton?(this.j||(this.j=new A6(this.api),this.j.Ea(this.Fa("ytp-offline-slate-buttons")),g.L(this,this.j)),Fob(this.j,b.actionButtons&&b.actionButtons[0],b.reminderButton)):this.j&&Fob(this.j,null,null);this.B=a}else this.B=null;this.G_()};
g.k.G_=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Tb(),d=this.getVideoData();b=d.isLivePlayback&&(g.RL(c)||g.VG(c,2)||g.VG(c,64));var e=2===d.autonavState&&g.VG(c,2);c=c.isPlaying()&&!g.ET(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.B?this.Gb?(null==a?0:g.XG(a,2))&&!this.getVideoData().Ol&&(g.ou(this.element,"ytp-offline-slate-collapsed"),this.D.stop(),g.ou(this.C,"ytp-offline-slate-bar-fade"),this.G.start()):(this.show(),this.D.start(),this.api.oa("offlineslatestatechange"),
this.K&&this.api.dB()):this.Gb&&(this.hide(),this.api.oa("offlineslatestatechange"))};
g.k.C_=function(){var a,b,c,d,e=null==(a=this.B)?void 0:null==(b=a.liveStreamability)?void 0:null==(c=b.liveStreamabilityRenderer)?void 0:null==(d=c.offlineSlate)?void 0:d.liveStreamOfflineSlateRenderer;e&&(a=Math.floor(g.ib()/1E3),b=e.canShowCountdown&&Number(e.scheduledStartTime),!b||b<=a?(Mob(this,e),this.countdownTimer.stop()):(Mob(this,e,g.dH(b-a)),g.fu(this.countdownTimer)))};
g.k.ya=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.U.prototype.ya.call(this)};C6.prototype.B=function(a){return this.trigger&&a.trigger?this.module===a.module&&this.trigger===a.trigger&&this.j===a.j:!1};
C6.prototype.isExpired=function(){return 6E4<(0,g.GD)()-this.C};
C6.prototype.toString=function(){return this.module+":"+this.trigger+":"+this.j};g.w(Uob,g.xV);g.k=Uob.prototype;g.k.ya=function(){G6(this);this.player.hf("heartbeat");g.xV.prototype.ya.call(this)};
g.k.onCueRangeEnter=function(){this.N=!0;E6(this,2E3)};
g.k.sE=function(a){this.heartbeatParams=a;E6(this,2E3)};
g.k.e1=function(a){var b;8!==this.player.getPresentingPlayerType()&&"UNPLAYABLE"!==(null==(b=this.j)?void 0:b.status)&&(g.VG(a.state,2)||g.VG(a.state,64)?(G6(this),this.D&&(this.N=!0,E6(this,1E3))):(g.VG(a.state,1)||g.VG(a.state,8))&&E6(this,2E3))};
g.k.f1=function(){3!==this.player.getPresentingPlayerType()&&E6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.wl=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.BI=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.rD("heartbeatActionPlayerTransitioned",a)};
g.k.uf=function(a){var b="LICENSE",c=Xob(a);if(c)return c.reason||g.VV[b]||"";(a=a.match(Yob))&&(a=Number(a[1]))&&(b=g.PAa(a));return g.VV[b]||""};
g.k.JD=function(){return!!this.offlineSlate&&this.offlineSlate.Gb};
var Yob=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.wV("heartbeat",Uob);})(_yt_player);
